# Generated by Django 5.2.12 on 2026-09-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_conversation_attachment_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
