# Generated by Django 5.2.12 on 2026-09-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_video_and_image_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='caption',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
