# Generated by Django 5.2.12 on 2026-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_request_accepted', 'Follow Request Accepted'), ('message', 'Message'), ('story', 'Story'), ('story_view', 'Story View'), ('story_reaction', 'Story Reaction'), ('story_reply', 'Story Reply')], default='like', max_length=40),
        ),
    ]
